### PR TITLE
Added support for MyXQL package (mariaex package was removed)

### PR DESCRIPTION
**Pull request by femz12**
Added support for MyXQL package (mariaex package was removed)

### CODE REVIEW

**Comment by kelvinst** [comment]
Hey @femz12, can you please check the errors that happened on CI and fix? Thanks for the PR btw!

**Comment by femz12** [comment]
> Hey @femz12, can you please check the errors that happened on CI and fix? Thanks for the PR btw!

Okay I will take a look

**Comment by lcacciagioni** [comment]
Any updates in regards to this feature?

**Comment by femz12** [comment]
So all tests passed locally but I an error occurred on travis CI - I don't know if I can run travis locally so I can see any error before merging - I can try it again today.

**Comment by femz12** [comment]
@kelvinst can you help review and merge?

**Comment by lcacciagioni** [comment]
Given that @kelvinst does not belong anymore to the organization that owns this project, I would say that maybe @keviinlouis, @luizpaulolppa or @petersonfs must review and approve the pull request. Is that possible guys? This is a killer feature that @femz12 had already implemented and it is working also for me locally at least.

**Comment by kelvinst** [comment]
I don't belong to the organization anymore but I do have admin access to the repo. Sorry for the time I took, I am pretty busy now and getting into vacations soon. I'm reviewing it, but can't promise a release before 2021.

**Review by kelvinst — APPROVED** [review]
LGTM>

**Comment by kelvinst** [comment]
@femz12 thanks for all the work and again, sorry for the delay answering those last messages

**Comment by femz12** [comment]
Thanks for merging @kelvinst

**Comment by lcacciagioni** [comment]
@kelvinst should we maybe create a new version given the support of the myxql package? and deploy it to hex.pm?

**Comment by femz12** [comment]
Yes please - I think it must be a new version

**Pull request merged**
