### PR TITLE
fix: do not use Mix during runtime

### LINKED ISSUE #45: Mix.Project.deps_paths/0 not found deploying with edeliver
Any idea on how to deploy this with edeliver? Whenever I ran `mix edeliver migrate staging` it does not run the tenant migrations.

Any help would be greatly appreciated.

Thanks!

### PR DESCRIPTION
**Pull request by dustinfarris**
Fixes #45.

I'm not sure if this is the best approach, but I think it could be a workaround at least.

There are still a couple failing tests I am working to resolve.

### CODE REVIEW

**Comment by dustinfarris** [comment]
I fixed the tests and squashed the commits.  I've also tried it out on my staging server and I am able to create tenants and run migrations.  This is ready for review and testing.

To try it out, use my fork of triplex:

```ex
# mix.exs
{:triplex, github: "dustinfarris/triplex", ref: "1340d22"},
```

```
mix do deps.clean triplex, deps.get
```

Everything should be the same, except it now works in OTP releases.  Please report back if it works or does not.

/cc @vinceurag @kelvinst

**Comment by vinceurag** [comment]
Thanks for this @dustinfarris. I'm on my work now and will be trying this. Will get back to you with results. Have a nice day!

**Comment by vinceurag** [comment]
@dustinfarris I just tested it now. It works!! Thank you!

@kelvinst I verify that this fix works. :)

**Comment by kelvinst** [comment]
@dustinfarris thanks for the fix! I'm merging it to master now and will do a release until the weekend!

**Comment by kelvinst** [comment]
@dustinfarris can you please rebase it with the current master?

**Comment by kelvinst** [comment]
@reimo can you check if this fixed #41 too? It guess it has, can you check it please?

**Comment by kelvinst** [comment]
@dustinfarris, I've added some adjusts to you code... 😉

**Comment by reimo** [comment]
@kelvinst got my forked repo to work 2 days ago, was hoping to make a pr later this week
Anyway, hope this PR sort that.

**Comment by dustinfarris** [comment]
@kelvinst rebased!

**Comment by kelvinst** [comment]
Perfect! :)

**Pull request merged**
